name: 'parameterized_model_examples'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  # The `start_date` variable will be accessible in all resources
  customer_name: "{{env_var('DBT_CUSTOMER_NAME', 'NONE')}}"
  customer_country_name: "{{env_var('DBT_CUSTOMER_COUNTRY_NAME', 'NONE')}}"


models:
  parameterized_model_examples:
    # Applies to all files under models/example/
    customer_data_products:
